### ISSUE TITLE
SPI3D not valid

### ISSUE THREAD

**Issue by sobotka** [cameramanben/LUTCalc#1]
Generates invalid float SPI3D LUTs. SPI3D format requires the cube size after dimension size. For example, for 64 it would be:

SPILUT 1.0
3 3
64 64 64

**Comment by cameramanben** [comment]
Oops! Seems an unnecessary extra variable broke the header code - the dimension line was getting made (I knew about it for the parser), just not being added to the overall file string. D'oh. Fixed in seconds (I hope!), but many, many thanks for pointing out something that could otherwise have stayed broken indefinitely.

I'm submitting an update with a few extras (hypergamma and hybrid log options, plus Rec709(800%) as an input gamma), so I've added the spi3d fix. I've uploaded it to the GitHub repo, and it is also up on lutcalc.net/testing,

Ben

**Comment by cameramanben** [comment]
The corrected version (v2.3.7) is now up in the main repo, in the LUTCalc For Mac project, online at lutcalc.net and in the Mac App Store and Chrome Web App versions.

If there is still any trouble let me know, but I'm going to close this for now,

Ben
